import { afterEach, describe, expect, test } from "bun:test";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";

import { collectCleanerEnvironmentEvidence } from "../ein-pi/agent/lib/cleaner-environment-evidence.ts";
import { collectCleanerTestEvidence, planCleanerTestEvidence, type CleanerTestBinding } from "../ein-pi/agent/lib/cleaner-test-evidence.ts";

const roots: string[] = [];
function fixture(pkg: unknown = { packageManager: "bun@1.3.0" }): string { const root = mkdtempSync(join(tmpdir(), "ein-cleaner-tests-")); roots.push(root); execFileSync("git", ["init", "-q"], { cwd: root }); execFileSync("git", ["config", "user.email", "fixture@example.com"], { cwd: root }); execFileSync("git", ["config", "user.name", "Fixture"], { cwd: root }); writeFileSync(join(root, "package.json"), JSON.stringify(pkg)); mkdirSync(join(root, "tests")); writeFileSync(join(root, "tests/example.test.ts"), "export {}\n"); execFileSync("git", ["add", "."], { cwd: root }); execFileSync("git", ["commit", "-qm", "fixture"], { cwd: root }); return root; }
function snapshot(root: string): string[] { const visit = (dir: string): string[] => readdirSync(dir).flatMap((name) => { const full = join(dir, name); if (relative(root, full).startsWith(".git")) return []; return statSync(full).isDirectory() ? visit(full) : [`${relative(root, full)}:${readFileSync(full).toString("hex")}`]; }); return visit(root).sort(); }
function setup(): { root: string; artifact: string; environment: ReturnType<typeof collectCleanerEnvironmentEvidence>; plan: ReturnType<typeof planCleanerTestEvidence>; binding: CleanerTestBinding } { const root = fixture(); const artifact = join(tmpdir(), `ein-results-${roots.length}.xml`); roots.push(artifact); const environment = collectCleanerEnvironmentEvidence(root); const plan = planCleanerTestEvidence(environment, { runner: "bun", format: "junit", scope: { files: ["tests/example.test.ts"] }, outputPath: artifact }); return { root, artifact, environment, plan, binding: { preStateRef: environment.sourceState.stateRef, postStateRef: environment.sourceState.stateRef, exitCode: 0 } }; }
afterEach(() => { for (const path of roots.splice(0)) rmSync(path, { recursive: true, force: true }); });

describe("Cleaner test evidence", () => {
	test("plans exact bounded Bun argv and rejects deceptive scope and internal output", () => { const { root, artifact, environment, plan } = setup(); expect(plan.status).toBe("available"); expect(plan.argv).toEqual(["bun", "test", "tests/example.test.ts", "--reporter=junit", `--reporter-outfile=${artifact}`]); expect(() => planCleanerTestEvidence(environment, { runner: "bun", format: "junit", scope: { files: ["--preload=evil"] }, outputPath: artifact })).toThrow(); expect(() => planCleanerTestEvidence(environment, { runner: "bun", format: "junit", scope: { files: ["tests/example.test.ts"] }, outputPath: join(root, "result.xml") })).toThrow(); });

	test("normalizes Bun JUnit pass, fail, skip, duration, and bounded sanitized failures", () => { const context = setup(); writeFileSync(context.artifact, `<testsuites tests="4" failures="2" skipped="1"><testsuite name="tests/example.test.ts" tests="4" failures="2" skipped="1"><testcase name="passes" time="0.01"/><testcase name="fails a" time="0.02"><failure message="\u001b[31m${"x".repeat(30)}\u001b[0m"/></testcase><testcase name="fails b" time="0.03"><failure>second failure</failure></testcase><testcase name="skips" time="0"><skipped/></testcase></testsuite></testsuites>`); const evidence = collectCleanerTestEvidence(context.environment, context.plan, context.artifact, context.binding, { maxFailures: 1, maxMessageChars: 10 }); expect(evidence.result).toMatchObject({ suites: 1, tests: 4, passed: 1, failed: 2, skipped: 1, durationMs: 60, failuresTruncated: true }); expect(evidence.result?.failures).toEqual([{ path: "tests/example.test.ts", name: "fails a", message: "xxxxxxxxxx" }]); });

	test("ingests the sanitized Bun 1.3.14 reporter fixture with its XML declaration", () => { const context = setup(); writeFileSync(context.artifact, readFileSync(join(import.meta.dir, "fixtures/bun-1.3.14-junit.xml"))); const evidence = collectCleanerTestEvidence(context.environment, context.plan, context.artifact, context.binding); expect(evidence.result).toMatchObject({ suites: 1, tests: 1, passed: 1, failed: 0, skipped: 0, durationMs: 1.629 }); });

	test("normalizes the documented narrow Vitest JSON shape", () => { const root = fixture({ devDependencies: { vitest: "^4" } }); const bin = join(root, "node_modules/.bin"); mkdirSync(bin, { recursive: true }); writeFileSync(join(bin, "vitest"), ""); const artifact = join(tmpdir(), "ein-vitest-results.json"); roots.push(artifact); const environment = collectCleanerEnvironmentEvidence(root); const plan = planCleanerTestEvidence(environment, { runner: "vitest", format: "json", scope: { files: ["tests/example.test.ts"] }, outputPath: artifact }); const assertions = [{ ancestorTitles: [], fullName: "passes", status: "passed", title: "passes", duration: 2, failureMessages: [], location: null, meta: {}, tags: [], benchmarks: [] }, { ancestorTitles: [], fullName: "fails", status: "failed", title: "fails", duration: 3, failureMessages: ["nope"], location: null, meta: {}, tags: [], benchmarks: [] }, { ancestorTitles: [], fullName: "skips", status: "skipped", title: "skips", duration: null, failureMessages: [], location: null, meta: {}, tags: [], benchmarks: [] }]; writeFileSync(artifact, JSON.stringify({ numTotalTestSuites: 1, numPassedTestSuites: 0, numFailedTestSuites: 1, numPendingTestSuites: 0, numTotalTests: 3, numPassedTests: 1, numFailedTests: 1, numPendingTests: 1, numTodoTests: 0, snapshot: {}, startTime: 1, success: false, testResults: [{ assertionResults: assertions, startTime: 1, endTime: 6, status: "failed", message: "", name: "tests/example.test.ts" }] })); const binding = { preStateRef: environment.sourceState.stateRef, postStateRef: environment.sourceState.stateRef, exitCode: 1 }; const result = collectCleanerTestEvidence(environment, plan, artifact, binding).result; expect(result).toMatchObject({ tests: 3, passed: 1, failed: 1, skipped: 1, durationMs: null }); expect(result?.failures).toEqual([{ path: "tests/example.test.ts", name: "fails", message: "nope" }]); });

	test("reports Vitest planning unavailable without a proven local executable", () => { const root = fixture({ devDependencies: { vitest: "^4" } }); const environment = collectCleanerEnvironmentEvidence(root); expect(planCleanerTestEvidence(environment, { runner: "vitest", format: "json", scope: { files: ["tests/example.test.ts"] }, outputPath: join(tmpdir(), "v.json") })).toMatchObject({ status: "unavailable", reason: "vitest-executable-unproven" }); });

	test("rejects malformed, entity-bearing, declaration-ambiguous, conflicting, and traversing artifacts", () => { for (const source of ["<testsuites>", `<!DOCTYPE x [<!ENTITY e SYSTEM "file:///etc/passwd">]><testsuite name="tests/example.test.ts" tests="0"/>`, `<?xml version="1.1" encoding="UTF-8"?><testsuite name="tests/example.test.ts"/>`, `<?xml version="1.0" encoding="ISO-8859-1"?><testsuite name="tests/example.test.ts"/>`, `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><testsuite name="tests/example.test.ts"/>`, `<?xml version="1.0" encoding="UTF-8"?>\n<?xml version="1.0" encoding="UTF-8"?><testsuite name="tests/example.test.ts"/>`, `<testsuite name="tests/example.test.ts"><?xml version="1.0" encoding="UTF-8"?></testsuite>`, `<testsuite name="../escape.test.ts" tests="0"/>`, `<testsuite name="tests/example.test.ts" tests="2"><testcase name="one"/></testsuite>`]) { const context = setup(); writeFileSync(context.artifact, source); expect(() => collectCleanerTestEvidence(context.environment, context.plan, context.artifact, context.binding)).toThrow(); } const context = setup(); writeFileSync(context.artifact, "x".repeat(30)); expect(() => collectCleanerTestEvidence(context.environment, context.plan, context.artifact, context.binding, { maxArtifactBytes: 20 })).toThrow(); });

	test("rejects unsupported Vitest claims, absolute paths, and runner mismatch", () => { const root = fixture({ devDependencies: { vitest: "^4" } }); const bin = join(root, "node_modules/.bin"); mkdirSync(bin, { recursive: true }); writeFileSync(join(bin, "vitest"), ""); const artifact = join(tmpdir(), "ein-invalid-vitest.json"); roots.push(artifact); const environment = collectCleanerEnvironmentEvidence(root); const plan = planCleanerTestEvidence(environment, { runner: "vitest", format: "json", scope: { files: ["tests/example.test.ts"] }, outputPath: artifact }); const binding = { preStateRef: environment.sourceState.stateRef, postStateRef: environment.sourceState.stateRef }; const base = { numTotalTestSuites: 0, numPassedTestSuites: 0, numFailedTestSuites: 0, numPendingTestSuites: 0, numTotalTests: 0, numPassedTests: 0, numFailedTests: 0, numPendingTests: 0, numTodoTests: 0, success: true, testResults: [] }; writeFileSync(artifact, JSON.stringify({ ...base, inventedPasses: 3 })); expect(() => collectCleanerTestEvidence(environment, plan, artifact, binding)).toThrow("Unsupported"); writeFileSync(artifact, JSON.stringify({ ...base, numTotalTestSuites: 1, numPassedTestSuites: 1, testResults: [{ assertionResults: [], startTime: 1, endTime: 1, status: "passed", message: "", name: "/absolute.test.ts" }] })); expect(() => collectCleanerTestEvidence(environment, plan, artifact, binding)).toThrow("Unsafe"); writeFileSync(artifact, "<testsuite/>"); expect(() => collectCleanerTestEvidence(environment, plan, artifact, binding)).toThrow("mismatch"); });

	test("requires fresh binding, keeps stable identities, freezes output, and stays read-only", () => { const context = setup(); writeFileSync(context.artifact, `<testsuite name="tests/example.test.ts" tests="1" failures="0" skipped="0"><testcase name="passes" time="0.01"/></testsuite>`); const before = snapshot(context.root); const unbound = collectCleanerTestEvidence(context.environment, context.plan, context.artifact); expect(unbound).toMatchObject({ status: "unavailable", freshness: "unavailable", reason: "invocation-unbound" }); const first = collectCleanerTestEvidence(context.environment, context.plan, context.artifact, context.binding); const second = collectCleanerTestEvidence(context.environment, context.plan, context.artifact, context.binding); expect(first).toEqual(second); expect(Object.isFrozen(first.result?.failures)).toBe(true); expect(snapshot(context.root)).toEqual(before); writeFileSync(join(context.root, "tests/example.test.ts"), "changed"); const stale = collectCleanerTestEvidence(context.environment, context.plan, context.artifact, context.binding); expect(stale).toMatchObject({ status: "unavailable", freshness: "stale", reason: "source-state-changed" }); });
});
