import { afterEach, describe, expect, test } from "bun:test";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";

import { collectCleanerComplexityEvidence } from "../ein-pi/agent/lib/cleaner-complexity-evidence.ts";
import { collectCleanerEnvironmentEvidence } from "../ein-pi/agent/lib/cleaner-environment-evidence.ts";

const roots: string[] = [];
function fixture(files: Record<string, string>) { const root = mkdtempSync(join(tmpdir(), "ein-complexity-")); roots.push(root); execFileSync("git", ["init", "-q"], { cwd: root }); execFileSync("git", ["config", "user.email", "fixture@example.com"], { cwd: root }); execFileSync("git", ["config", "user.name", "Fixture"], { cwd: root }); writeFileSync(join(root, "package.json"), "{}"); for (const [path, source] of Object.entries(files)) { mkdirSync(join(root, path, ".."), { recursive: true }); writeFileSync(join(root, path), source); } execFileSync("git", ["add", "."], { cwd: root }); execFileSync("git", ["commit", "-qm", "fixture"], { cwd: root }); return { root, environment: collectCleanerEnvironmentEvidence(root) }; }
function snapshot(root: string): string[] { const visit = (dir: string): string[] => readdirSync(dir).flatMap((name) => { const full = join(dir, name); if (relative(root, full).startsWith(".git")) return []; return statSync(full).isDirectory() ? visit(full) : [`${relative(root, full)}:${readFileSync(full).toString("hex")}`]; }); return visit(root).sort(); }
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); });

describe("Cleaner function complexity evidence", () => {
	test("counts the documented decisions and excludes nested functions from parents", () => { const context = fixture({ "src/all.ts": `export function outer(x: number) { if (x) x++; for (;;) break; while (x) x--; do x++; while (x < 2); switch (x) { case 1: break; default: break } try {} catch {} const y = x ? 1 : 2; const z = x && y || 2 ?? 3; function inner() { if (x) return 1 } return z }` }); const evidence = collectCleanerComplexityEvidence(context.environment); expect(evidence.functions.map(({ displayName, complexity }) => [displayName, complexity])).toEqual([["outer", 11], ["inner", 2]]); expect(evidence.functions[0]?.decisions.categories).toEqual({ if: 1, loop: 3, "case-non-default": 1, catch: 1, conditional: 1, "logical-and": 1, "logical-or": 1, "nullish-coalescing": 1 }); expect(evidence.aggregate).toEqual({ count: 2, max: 11, distribution: [{ complexity: 2, count: 1 }, { complexity: 11, count: 1 }] }); });

	test("provides stable exact identities, method and anonymous fallbacks, and same-line mapping ambiguity", () => { const context = fixture({ "src/names.ts": "export const a = () => 1, b = () => 2; export default [function () {}, function () {}]; class C { run() {}; constructor() {} }\n" }); const first = collectCleanerComplexityEvidence(context.environment), second = collectCleanerComplexityEvidence(context.environment); expect(first).toEqual(second); expect(first.functions.map((fn) => fn.displayName)).toEqual(["a", "b", "<anonymous@1:56>", "<anonymous@1:72>", "run", "constructor"]); expect(first.functions.slice(0, 4).every((fn) => fn.coverageMapping.ambiguous)).toBe(true); expect(first.functions.every((fn) => fn.identity.startsWith("function-v1:sha256:"))).toBe(true); expect(Object.isFrozen(first.functions[0]?.decisions.categories)).toBe(true); });

	test("parses TSX and JSX by filename and rejects malformed source", () => { const good = fixture({ "src/a.tsx": "export const View = () => <div>{true ? 1 : 2}</div>", "src/b.jsx": "export function B() { return <span /> }" }); expect(collectCleanerComplexityEvidence(good.environment).functions.map((fn) => fn.complexity)).toEqual([2, 1]); const bad = fixture({ "src/bad.ts": "export function broken( {" }); expect(() => collectCleanerComplexityEvidence(bad.environment)).toThrow("Malformed source"); });

	test("extracts bounded Vue script blocks with original offsets", () => { const context = fixture({ "src/App.vue": `<template><p /></template>\n<script>\nexport function regular() { if (true) return 1 }\n</script>\n<script setup lang="ts">\nconst setup = () => true ? 1 : 2\n</script>` }); const functions = collectCleanerComplexityEvidence(context.environment).functions; expect(functions.map((fn) => [fn.displayName, fn.span.startLine, fn.complexity])).toEqual([["regular", 3, 2], ["setup", 6, 2]]); });

	test("rejects unsafe or ambiguous Vue forms", () => { for (const source of ["<script src='x.ts'></script>", "<script></script><script></script>", "<script lang='coffee'></script>", "<script>", "<script setup='yes'></script>"]) { const context = fixture({ "src/App.vue": source }); expect(() => collectCleanerComplexityEvidence(context.environment)).toThrow(); } });

	test("extracts Astro frontmatter and inline scripts with offsets", () => { const context = fixture({ "src/Page.astro": `---\nexport function front() { if (true) return 1 }\n---\n<div />\n<script lang="ts">\nconst inline = () => true && false\n</script>` }); expect(collectCleanerComplexityEvidence(context.environment).functions.map((fn) => [fn.displayName, fn.span.startLine, fn.complexity])).toEqual([["front", 2, 2], ["inline", 6, 2]]); });

	test("rejects unsafe Astro forms and never parses template expressions", () => { const safe = fixture({ "src/Page.astro": "<div>{() => true ? 1 : 2}</div>" }); expect(collectCleanerComplexityEvidence(safe.environment).functions).toEqual([]); for (const source of ["---\nconst x = 1", " \n---\nconst x = 1\n---", "<script src='x.ts'></script>", "<script type='text/babel'></script>", "<script lang='coffee'></script>", "<script>"]) { const context = fixture({ "src/Page.astro": source }); expect(() => collectCleanerComplexityEvidence(context.environment)).toThrow(); } });

	test("rejects noncurrent, excluded, forged, and over-budget sources and remains read-only", () => { const context = fixture({ "src/a.ts": "export const a = () => 1", "dist/no.ts": "export const no = () => 1" }); const before = snapshot(context.root); expect(() => collectCleanerComplexityEvidence(context.environment, ["dist/no.ts"])).toThrow("outside current bounded"); expect(() => collectCleanerComplexityEvidence(context.environment, undefined, { maxBytes: 1 })).toThrow("byte budget"); expect(() => collectCleanerComplexityEvidence(context.environment, undefined, { maxFunctions: 1 })).not.toThrow(); const wrongDigest = { ...context.environment, scope: { ...context.environment.scope, files: context.environment.scope.files.map((file) => file.path === "src/a.ts" ? { ...file, sha256: "0".repeat(64) } : file) } }; expect(() => collectCleanerComplexityEvidence(wrongDigest)).toThrow("digest is stale"); const escaped = { ...context.environment, scope: { ...context.environment.scope, files: [{ path: "/etc/hosts", sha256: "0".repeat(64) }] } }; expect(() => collectCleanerComplexityEvidence(escaped)).toThrow("escapes environment scope"); expect(snapshot(context.root)).toEqual(before); writeFileSync(join(context.root, "src/a.ts"), "changed"); expect(() => collectCleanerComplexityEvidence(context.environment)).toThrow("state is stale"); });
});
