import { afterEach, describe, expect, test } from "bun:test";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";

import { collectCleanerCoverageEvidence, planCleanerCoverageEvidence } from "../ein-pi/agent/lib/cleaner-coverage-evidence.ts";
import { collectCleanerEnvironmentEvidence } from "../ein-pi/agent/lib/cleaner-environment-evidence.ts";
import { collectCleanerTestEvidence, planCleanerTestEvidence, type CleanerTestBinding } from "../ein-pi/agent/lib/cleaner-test-evidence.ts";

const cleanup: string[] = [];
function fixture(vitest = false) { const root = realpathSync(mkdtempSync(join(tmpdir(), "ein-coverage-project-"))), output = realpathSync(mkdtempSync(join(tmpdir(), "ein-coverage-output-"))); cleanup.push(root, output); execFileSync("git", ["init", "-q"], { cwd: root }); execFileSync("git", ["config", "user.email", "fixture@example.com"], { cwd: root }); execFileSync("git", ["config", "user.name", "Fixture"], { cwd: root }); writeFileSync(join(root, "package.json"), JSON.stringify(vitest ? { devDependencies: { vitest: "^4" } } : { packageManager: "bun@1.3.0" })); mkdirSync(join(root, "src")); mkdirSync(join(root, "tests")); writeFileSync(join(root, "src/a.ts"), "export function same() { return 1 }\n"); writeFileSync(join(root, "src/b.ts"), "export const b = () => 2\n"); writeFileSync(join(root, "tests/example.test.ts"), "export {}\n"); if (vitest) { mkdirSync(join(root, "node_modules/.bin"), { recursive: true }); writeFileSync(join(root, "node_modules/.bin/vitest"), ""); } execFileSync("git", ["add", "."], { cwd: root }); execFileSync("git", ["commit", "-qm", "fixture"], { cwd: root }); const environment = collectCleanerEnvironmentEvidence(root); const resultPath = join(output, vitest ? "results.json" : "results.xml"); const basePlan = planCleanerTestEvidence(environment, { runner: vitest ? "vitest" : "bun", format: vitest ? "json" : "junit", scope: { files: ["tests/example.test.ts"], selectors: ["exact test"] }, outputPath: resultPath }); const plan = planCleanerCoverageEvidence(environment, basePlan, { outputDirectory: output }); const binding: CleanerTestBinding = { preStateRef: environment.sourceState.stateRef, postStateRef: environment.sourceState.stateRef, exitCode: 0 }; return { root, output, environment, plan, resultPath, artifact: join(output, "lcov.info"), binding }; }
function testEvidence(context: ReturnType<typeof fixture>, failed = false) { if (context.plan.testPlan?.runner === "bun") writeFileSync(context.resultPath, `<testsuite name="tests/example.test.ts" tests="1" failures="${failed ? 1 : 0}" skipped="0"><testcase name="exact test">${failed ? "<failure>nope</failure>" : ""}</testcase></testsuite>`); else writeFileSync(context.resultPath, JSON.stringify({ numTotalTestSuites: 1, numPassedTestSuites: failed ? 0 : 1, numFailedTestSuites: failed ? 1 : 0, numPendingTestSuites: 0, numTotalTests: 1, numPassedTests: failed ? 0 : 1, numFailedTests: failed ? 1 : 0, numPendingTests: 0, numTodoTests: 0, success: !failed, testResults: [{ assertionResults: [{ ancestorTitles: [], fullName: "exact test", status: failed ? "failed" : "passed", title: "exact test", duration: 1, failureMessages: failed ? ["nope"] : [], location: null, meta: {}, tags: [], benchmarks: [] }], startTime: 1, endTime: 2, status: failed ? "failed" : "passed", message: "", name: "tests/example.test.ts" }] })); const binding = { ...context.binding, exitCode: failed ? 1 : 0 }; return { evidence: collectCleanerTestEvidence(context.environment, context.plan.testPlan!, context.resultPath, binding), binding }; }
function snapshot(root: string): string[] { const visit = (dir: string): string[] => readdirSync(dir).flatMap((name) => { const full = join(dir, name); if (relative(root, full).startsWith(".git")) return []; return statSync(full).isDirectory() ? visit(full) : [`${relative(root, full)}:${readFileSync(full).toString("hex")}`]; }); return visit(root).sort(); }
afterEach(() => { for (const path of cleanup.splice(0)) rmSync(path, { recursive: true, force: true }); });

describe("Cleaner LCOV coverage evidence", () => {
	test("plans exact Bun and proven-local Vitest argv with caller-controlled lcov.info", () => { const bun = fixture(); expect(bun.plan.argv).toEqual(["bun", "test", "tests/example.test.ts", "--test-name-pattern", "^(?:exact test)$", "--reporter=junit", `--reporter-outfile=${bun.resultPath}`, "--coverage", "--coverage-reporter=lcov", `--coverage-dir=${bun.output}`]); const vitest = fixture(true); expect(vitest.plan.argv).toEqual([join(vitest.root, "node_modules/.bin/vitest"), "run", "tests/example.test.ts", "-t", "^(?:exact test)$", "--reporter=json", `--outputFile=${vitest.resultPath}`, "--coverage.enabled", "--coverage.reporter=lcov", `--coverage.reportsDirectory=${vitest.output}`]); expect(vitest.plan.artifactPath).toBe(join(vitest.output, "lcov.info")); expect(() => planCleanerCoverageEvidence(bun.environment, bun.plan.testPlan!, { outputDirectory: bun.root })).toThrow(); });

	test("normalizes multi-file lines, branches, functions, zero denominators, totals, and provisional identities", () => { const context = fixture(); const linked = testEvidence(context); writeFileSync(context.artifact, "TN:\nSF:src/b.ts\nDA:1,0\nLF:1\nLH:0\nFNF:2\nFNH:1\nend_of_record\nSF:src/a.ts\nFN:1,same\nFNDA:2,same\nDA:1,3\nDA:2,0\nBRDA:1,0,0,1\nBRDA:1,0,1,-\nFNF:1\nFNH:1\nend_of_record\n"); const evidence = collectCleanerCoverageEvidence(context.environment, context.plan, linked.evidence, context.artifact, linked.binding); expect(evidence.files.map((file) => file.path)).toEqual(["src/a.ts", "src/b.ts"]); expect(evidence.files[0]?.lineRecords).toEqual([{ line: 1, hits: 3 }, { line: 2, hits: 0 }]); expect(evidence.totals).toEqual({ lines: { found: 3, hit: 1, percentage: 33.333333 }, branches: { found: 2, hit: 1, percentage: 50 }, functions: { found: 3, hit: 2, percentage: 66.666667 } }); expect(evidence.files[1]?.branches.percentage).toBeNull(); expect(evidence.files[1]?.functionRecords).toEqual([]); expect(evidence.files[0]?.functionRecords[0]).toMatchObject({ line: 1, name: "same", hits: 2, mapping: { confidence: "provisional-location", limitation: "lcov-name-and-line-not-ast-identity" } }); });

	test("rejects conflicting duplicates, malformed records, ambiguity, unsafe and unavailable sources", () => { const cases = ["SF:src/a.ts\nDA:1,1\nDA:1,2\nend_of_record\n", "SF:src/a.ts\nDA:1,-1\nend_of_record\n", "SF:../a.ts\nend_of_record\n", "SF:/tmp/a.ts\nend_of_record\n", "SF:dist/a.ts\nend_of_record\n", "SF:src/missing.ts\nend_of_record\n", "SF:src/a.ts\nFN:1,same\nFN:2,same\nFNDA:1,same\nend_of_record\n"]; for (const source of cases) { const context = fixture(); const linked = testEvidence(context); writeFileSync(context.artifact, source); expect(() => collectCleanerCoverageEvidence(context.environment, context.plan, linked.evidence, context.artifact, linked.binding)).toThrow(); } });

	test("enforces artifact and record budgets", () => { const context = fixture(); const linked = testEvidence(context); writeFileSync(context.artifact, "SF:src/a.ts\nDA:1,1\nend_of_record\n"); expect(() => collectCleanerCoverageEvidence(context.environment, context.plan, linked.evidence, context.artifact, linked.binding, { maxArtifactBytes: 10 })).toThrow("oversized"); expect(() => collectCleanerCoverageEvidence(context.environment, context.plan, linked.evidence, context.artifact, linked.binding, { maxRecords: 2 })).toThrow("budget"); });

	test("requires exact current linked test evidence and labels failed-test coverage without quality pass", () => { const context = fixture(); const linked = testEvidence(context, true); writeFileSync(context.artifact, "SF:src/a.ts\nDA:1,1\nend_of_record\n"); const failed = collectCleanerCoverageEvidence(context.environment, context.plan, linked.evidence, context.artifact, linked.binding); expect(failed).toMatchObject({ status: "available", reason: "tests-failed-coverage-only", qualityOutcome: "tests-failed" }); const unbound = collectCleanerCoverageEvidence(context.environment, context.plan, linked.evidence, context.artifact); expect(unbound).toMatchObject({ status: "unavailable", freshness: "stale", reason: "source-state-changed" }); const other = fixture(); const otherLinked = testEvidence(other); expect(collectCleanerCoverageEvidence(context.environment, context.plan, otherLinked.evidence, context.artifact, linked.binding)).toMatchObject({ status: "unavailable", reason: "test-evidence-unavailable" }); writeFileSync(join(context.root, "src/a.ts"), "changed\n"); expect(collectCleanerCoverageEvidence(context.environment, context.plan, linked.evidence, context.artifact, linked.binding)).toMatchObject({ status: "unavailable", freshness: "stale" }); });

	test("is deterministic, deeply frozen, digest-bound, and read-only", () => { const context = fixture(); const linked = testEvidence(context); writeFileSync(context.artifact, "SF:src/a.ts\nDA:1,1\nend_of_record\n"); const before = snapshot(context.root), first = collectCleanerCoverageEvidence(context.environment, context.plan, linked.evidence, context.artifact, linked.binding), second = collectCleanerCoverageEvidence(context.environment, context.plan, linked.evidence, context.artifact, linked.binding); expect(first).toEqual(second); expect(Object.isFrozen(first.files[0]?.sourceDigest)).toBe(true); expect(first.files[0]?.sourceDigest.digest).toBe(context.environment.scope.files.find((file) => file.path === "src/a.ts")!.sha256); expect(snapshot(context.root)).toEqual(before); });
});
