import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";

import { calculateCrap, deriveCleanerCrapEvidence } from "../ein-pi/agent/lib/cleaner-crap-evidence.ts";
import type { CleanerComplexityEvidence, CleanerFunctionComplexity } from "../ein-pi/agent/lib/cleaner-complexity-evidence.ts";
import type { CleanerCoverageEvidence } from "../ein-pi/agent/lib/cleaner-coverage-evidence.ts";

const digest = "a".repeat(64), stateRef = "state";
function identified<T extends object>(base: T): T & { outputIdentity: { algorithm: "sha256"; digest: string } } { return { ...base, outputIdentity: { algorithm: "sha256", digest: createHash("sha256").update(JSON.stringify(base)).digest("hex") } }; }
function fn(identity: string, path = "src/a.ts", startLine = 1, endLine = 3, complexity = 2, ambiguous = false): CleanerFunctionComplexity { return { identity, displayName: identity, path, span: { startLine, startColumn: 1, endLine, endColumn: 2 }, syntaxKind: "FunctionDeclaration", complexity, decisions: { total: complexity - 1, categories: {} }, coverageMapping: { declarationLine: startLine, confidence: "exact-ast-span", ambiguous } }; }
function packets(functions: CleanerFunctionComplexity[], lines: { line: number; hits: number }[], path = "src/a.ts"): [CleanerComplexityEvidence, CleanerCoverageEvidence] { const identity = { algorithm: "sha256" as const, digest: "b".repeat(64) }; const complexity = identified({ version: "cleaner-complexity-evidence/v1" as const, collectorKind: "function-cyclomatic-complexity" as const, definition: {} as CleanerComplexityEvidence["definition"], sourceState: { kind: "git-state" as const, stateRef, freshness: "current" as const }, scope: { identity: "scope", files: [{ path, sha256: digest }] }, functions, aggregate: { count: functions.length, max: 2, distribution: [] }, budget: {} as CleanerComplexityEvidence["budget"] }); const coverage = identified({ version: "cleaner-coverage-evidence/v1" as const, collectorKind: "lcov-coverage" as const, status: "available" as const, freshness: "current" as const, reason: "collected" as const, runner: "bun" as const, qualityOutcome: "tests-passed" as const, sourceState: { kind: "git-state" as const, stateRef, freshness: "current" as const }, testEvidenceIdentity: identity, files: [{ path, sourceDigest: { algorithm: "sha256" as const, digest }, lines: { found: lines.length, hit: lines.filter((line) => line.hits > 0).length, percentage: 0 }, lineRecords: lines, branches: { found: 0, hit: 0, percentage: null }, functions: { found: 0, hit: 0, percentage: null }, functionRecords: [] }], totals: { lines: { found: 0, hit: 0, percentage: null }, branches: { found: 0, hit: 0, percentage: null }, functions: { found: 0, hit: 0, percentage: null } }, artifactIdentity: identity, budget: {} as CleanerCoverageEvidence["budget"] }); return [complexity, coverage]; }

describe("Cleaner CRAP evidence", () => {
	test("uses the immutable standard formula with known values", () => { expect(calculateCrap(2, 1)).toBe(2); expect(calculateCrap(2, 0)).toBe(6); expect(calculateCrap(4, 0.5)).toBe(6); expect(() => calculateCrap(0, 1)).toThrow(); });
	test("measures full, partial, and zero exact-span line coverage", () => { for (const [hits, expected] of [[[1, 1, 1], 2], [[1, 0, 1], 2.148148], [[0, 0, 0], 6]] as const) { const [complexity, coverage] = packets([fn("f")], hits.map((value, index) => ({ line: index + 1, hits: value }))); const result = deriveCleanerCrapEvidence(complexity, coverage); expect(result.measured[0]?.crap).toBe(expected); expect(result.aggregate.count).toBe(1); } });
	test("calculates CRAP from the unrounded repeating coverage fraction", () => { const [complexity, coverage] = packets([fn("f", "src/a.ts", 1, 3, 100)], [{ line: 1, hits: 1 }, { line: 2, hits: 0 }, { line: 3, hits: 0 }]); const measured = deriveCleanerCrapEvidence(complexity, coverage).measured[0]!; expect(measured.coverageFraction).toBe(0.333333); expect(measured.crap).toBe(calculateCrap(100, 1 / 3)); expect(measured.crap).not.toBe(calculateCrap(100, measured.coverageFraction)); });
	test("records every unavailable mapping reason", () => { const functions = [fn("missing", "src/missing.ts"), fn("same", "src/a.ts", 1, 3, 2, true), fn("parent", "src/a.ts", 4, 8), fn("child", "src/a.ts", 5, 6), fn("none", "src/a.ts", 10, 11), fn("decl", "src/a.ts", 12, 12), fn("vue", "src/App.vue")]; const [rawComplexity, coverage] = packets(functions, [{ line: 1, hits: 1 }, { line: 2, hits: 1 }, { line: 3, hits: 1 }, { line: 5, hits: 1 }, { line: 6, hits: 0 }, { line: 12, hits: 1 }]); const { outputIdentity: _, ...base } = rawComplexity; const complexity = identified({ ...base, scope: { ...base.scope, files: [...base.scope.files, { path: "src/App.vue", sha256: digest }] } }); const result = deriveCleanerCrapEvidence(complexity, coverage); expect(result.measured.map((item) => item.functionIdentity)).toEqual(["child"]); expect(result.unavailable.map((item) => item.reason)).toEqual(["coverage-file-missing", "same-line-ambiguous", "nested-function-line-ambiguous", "no-da-denominator", "declaration-only-line-ambiguous", "coverage-file-missing"]); expect(result.aggregate.unavailableCount).toBe(6); });
	test("fails closed for framework offsets, source digest and global state mismatches", () => { const [vueComplexity, vueCoverage] = packets([fn("vue", "src/App.vue")], [{ line: 1, hits: 1 }, { line: 2, hits: 1 }], "src/App.vue"); expect(deriveCleanerCrapEvidence(vueComplexity, vueCoverage).unavailable[0]?.reason).toBe("framework-offset-unproven"); const [complexity, coverage] = packets([fn("f")], [{ line: 1, hits: 1 }, { line: 2, hits: 1 }]); const { outputIdentity: _, ...coverageBase } = coverage; const mismatched = identified({ ...coverageBase, sourceState: { ...coverage.sourceState, stateRef: "other" } }); expect(() => deriveCleanerCrapEvidence(complexity, mismatched)).toThrow("incompatible"); const wrongDigest = identified({ ...coverageBase, files: [{ ...coverage.files[0]!, sourceDigest: { algorithm: "sha256" as const, digest: "d".repeat(64) } }] }); expect(() => deriveCleanerCrapEvidence(complexity, wrongDigest)).toThrow("digest mismatch"); });
	test("is stable, deeply frozen, bounded, and rejects runtime-malformed metrics", () => { const inputs = packets([fn("f")], [{ line: 1, hits: 1 }, { line: 2, hits: 0 }]); const first = deriveCleanerCrapEvidence(...inputs), second = deriveCleanerCrapEvidence(...inputs); expect(first).toEqual(second); expect(first.measured[0]?.identity).toMatch(/^crap-function-v1:sha256:/); expect(Object.isFrozen(first.aggregate.distribution)).toBe(true); expect(() => deriveCleanerCrapEvidence(...inputs, { maxLineRecords: 1 })).toThrow("over-budget"); const { outputIdentity: _, ...coverageBase } = inputs[1]; const malformed = identified({ ...coverageBase, files: [{ ...inputs[1].files[0]!, lineRecords: [{ line: 1, hits: -1 }] }] }); expect(() => deriveCleanerCrapEvidence(inputs[0], malformed)).toThrow("Malformed"); });
});
