import { afterEach, describe, expect, test } from "bun:test";
import { closeSync, fsyncSync, lstatSync, mkdirSync, mkdtempSync, openSync, readFileSync, realpathSync, renameSync, rmSync, symlinkSync, unlinkSync, writeFileSync, writeSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runInstall } from "../installer/src/cli/install.ts";
import { executeInstallPlanJournaled, inspectInstallJournal, installJournalMatchesPlan, installJournalPath, installPlanDigest, InstallJournalError, validateInstallJournal, type InstallExecutionJournalV1, type InstallJournalFs } from "../installer/src/core/install-journal.ts";
import type { InstallPlanExecutionHandlers } from "../installer/src/core/install-executor.ts";
import { createInstallPlan, type InstallPlanInput, type InstallPlanV1 } from "../installer/src/core/install-plan.ts";

const roots: string[] = [];
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); });
const home = (): string => { const value = mkdtempSync(join(realpathSync(tmpdir()), "ein-install-journal-")); roots.push(value); return value; };
function plan(target: InstallPlanInput["target"] = "both", root = home()): InstallPlanV1 { return createInstallPlan({ target, home: root, piAgentDir: join(root, ".pi-ein", "agent"), piAgentDirExists: false, piOwnership: { status: "absent" }, claudeConfigHome: join(root, ".claude-ein"), platform: { os: "darwin", arch: "arm64" }, dependencies: { bun: false, pi: false, engram: false, gh: false, hypa: false, codegraph: false }, flags: { yes: true, noEngram: false, noSecrets: true, noHypa: false, noCodegraph: false, skipLinear: true } }); }
const handlers = (value: InstallPlanV1, call: (id: string) => { ok: boolean } = () => ({ ok: true })): InstallPlanExecutionHandlers => Object.fromEntries(value.inventory.map(({ id }) => [id, () => call(id)])) as InstallPlanExecutionHandlers;
const fsOps = (): InstallJournalFs => ({ read: (path) => readFileSync(path), mkdir: (path, mode) => mkdirSync(path, { mode }), open: (path, flags, mode) => openSync(path, flags, mode), write: (fd, data, offset) => writeSync(fd, data, offset, data.length - offset), fsync: fsyncSync, close: closeSync, rename: renameSync, unlink: unlinkSync, inspect: (path) => { try { const item = lstatSync(path); return { kind: item.isSymbolicLink() ? "symlink" : item.isFile() ? "file" : item.isDirectory() ? "directory" : "other", mode: item.mode & 0o777, size: item.size }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { kind: "missing", mode: 0, size: 0 }; throw error; } } });
function recovery(target: InstallPlanInput["target"], patterns: Partial<Record<"shared" | "pi" | "claude", string>>): InstallExecutionJournalV1 { const value = plan(target), indexes = { shared: 0, pi: 0, claude: 0 }, states = { c: "completed", f: "failed", p: "pending", n: "not-run" } as const; const entries = value.inventory.filter(({ state }) => state === "selected" || state === "conditional").map(({ id, runtime }) => ({ id, runtime, status: states[(patterns[runtime]?.[indexes[runtime]++] ?? "n") as keyof typeof states] })); const terminal = entries.find(({ status }) => status === "pending") ?? entries.find(({ status }) => status === "failed"); return { schemaVersion: 1, transactionId: "eeeeeeee-eeee-4eee-eeee-eeeeeeeeeeee", planDigest: installPlanDigest(value), target, platform: value.platform, state: "recovery-required", entries, pendingEntryId: terminal!.id, recoveryCode: entries.some(({ status }) => status === "failed") ? "handler-failed" : "interrupted" }; }

describe("install execution journal", () => {
  test("is closed, bounded, deterministic, and rejects malformed or private identity", async () => {
    const value = plan("claude"), tx = "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa";
    await executeInstallPlanJournaled(value, handlers(value, () => ({ ok: false })), { transactionId: () => tx });
    const status = inspectInstallJournal(value.home); expect(status.status).toBe("valid");
    const journal = status.status === "valid" ? status.journal : undefined; expect(journal?.transactionId).toBe(tx); expect(journal?.planDigest).toMatch(/^[0-9a-f]{64}$/); expect(installJournalMatchesPlan(journal!, value)).toBe(true); expect(installJournalMatchesPlan(journal!, plan("pi"))).toBe(false); expect(JSON.stringify(journal)).not.toMatch(/PRIVATE|stdout|stderr|environment|\.ein|\.atl/i);
    const revoked = Proxy.revocable({ ...journal }, {}); revoked.revoke(); const accessor = { ...journal }, entryAccessor = [...journal!.entries]; Object.defineProperty(accessor, "state", { enumerable: true, get: () => "prepared" }); Object.defineProperty(entryAccessor, "0", { enumerable: true, get: () => journal!.entries[0] }); const malformed: unknown[] = [{ ...journal, extra: true }, { ...journal, transactionId: "PRIVATE" }, { ...journal, planDigest: "PRIVATE" }, { ...journal, state: "prepared" }, { ...journal, state: "complete" }, { ...journal, entries: entryAccessor }, { ...journal, entries: [{ id: "private.entry", status: "pending" }], pendingEntryId: "private.entry" }, Object.assign(Object.create({ inherited: true }), journal), new Proxy({ ...journal }, {}), revoked.proxy, accessor];
    for (const candidate of malformed) expect(() => validateInstallJournal(candidate)).toThrow(InstallJournalError); const reordered = { inventory: value.inventory, blockers: value.blockers, status: value.status, platform: { arch: value.platform.arch, os: value.platform.os }, claudeConfigHome: value.claudeConfigHome, home: value.home, target: value.target, schemaVersion: 1 } as InstallPlanV1; expect(installPlanDigest(reordered)).toBe(installPlanDigest(value)); const path = installJournalPath(value.home), canonical = readFileSync(path, "utf8"); for (const noncanonical of [canonical.replace("{", '{"schemaVersion":1,'), ` ${canonical}`]) { writeFileSync(path, noncanonical, { mode: 0o600 }); expect(inspectInstallJournal(value.home)).toEqual({ status: "invalid" }); }
  });

  test("publishes prepared, pending, completion and honest Both failure snapshots", async () => {
    const value = plan(), snapshots: InstallExecutionJournalV1[] = [], base = fsOps();
    const traced: InstallJournalFs = { ...base, rename(from, to) { base.rename(from, to); snapshots.push(JSON.parse(new TextDecoder().decode(base.read(to))) as InstallExecutionJournalV1); } };
    const calls: string[] = []; const failed = "pi.dependency.pi";
    const result = await executeInstallPlanJournaled(value, handlers(value, (id) => { calls.push(id); return { ok: id !== failed }; }), { fs: traced, transactionId: () => "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb" });
    expect(result.ok).toBe(false); expect(calls).toContain("claude.deploy-runtime");
    expect(snapshots[0]?.state).toBe("prepared"); expect(snapshots[1]).toMatchObject({ state: "executing", pendingEntryId: "shared.dependency.bun" });
    const final = snapshots.at(-1)!; expect(final).toMatchObject({ state: "recovery-required", recoveryCode: "handler-failed", pendingEntryId: failed });
    expect(final.entries.find(({ id }) => id === failed)?.status).toBe("failed"); expect(final.entries.find(({ id }) => id === "claude.deploy-runtime")?.status).toBe("completed");
  });

  test("admits only reachable recovery states within and across runtime segments", () => {
    const valid = [recovery("pi", { shared: "c", pi: "p" }), recovery("pi", { shared: "c", pi: "ccp" }), recovery("claude", { shared: "c", claude: "p" }), recovery("both", { shared: "f" }), recovery("both", { shared: "c", pi: "f", claude: "cc" }), recovery("both", { shared: "c", pi: "ccf", claude: "f" }), recovery("both", { shared: "c", pi: "cccccccccccccccc", claude: "p" })];
    const invalid = [recovery("both", { shared: "c", pi: "cnc", claude: "f" }), recovery("both", { shared: "c", pi: "cfnc" }), recovery("both", { shared: "f", pi: "c" }), recovery("both", { shared: "c", pi: "n", claude: "p" }), recovery("both", { shared: "c", pi: "p", claude: "p" }), recovery("both", { shared: "c", pi: "ff" }), recovery("claude", { shared: "n", claude: "p" })];
    for (const journal of valid) expect(() => validateInstallJournal(journal)).not.toThrow(); for (const journal of invalid) expect(() => validateInstallJournal(journal)).toThrow(InstallJournalError); const absent = recovery("pi", { shared: "c", pi: "f" }); expect(() => validateInstallJournal({ ...absent, entries: [...absent.entries, { id: "claude.deploy-runtime", runtime: "claude", status: "not-run" }] })).toThrow(InstallJournalError);
  });

  test("persists bounded recovery for returned and thrown failures without raw detail", async () => {
    for (const throws of [false, true]) { const value = plan("pi"); await executeInstallPlanJournaled(value, handlers(value, (id) => { if (id !== "pi.dependency.pi") return { ok: true }; if (throws) throw new Error("PRIVATE raw path stdout"); return { ok: false, detail: "PRIVATE raw path stdout" } as { ok: boolean }; }), { transactionId: () => throws ? "cccccccc-cccc-4ccc-cccc-cccccccccccc" : "dddddddd-dddd-4ddd-dddd-dddddddddddd" }); const status = inspectInstallJournal(value.home); expect(status.status).toBe("valid"); expect(JSON.stringify(status)).toContain("handler-failed"); expect(JSON.stringify(status)).not.toContain("PRIVATE"); }
  });

  test("retains verified completion and reports every publication fault", async () => {
    const operations = ["inspect", "mkdir", "open", "write", "fsync", "close", "rename", "read"] as const;
    for (const operation of operations) { const value = plan("claude"), base = fsOps(); let calls = 0; const fault = { ...base, [operation]: (...args: unknown[]) => { calls += 1; if (calls === 1) throw new Error("fault"); return (base[operation] as (...inner: unknown[]) => unknown)(...args); } } as InstallJournalFs; await expect(executeInstallPlanJournaled(value, handlers(value), { fs: fault })).rejects.toBeInstanceOf(InstallJournalError); expect(calls).toBeGreaterThan(0); }
    const value = plan("claude"), base = fsOps(); let unlinks = 0; await executeInstallPlanJournaled(value, handlers(value), { fs: { ...base, unlink(path) { unlinks += 1; base.unlink(path); } } }); const receipt = inspectInstallJournal(value.home); expect(receipt.status).toBe("valid"); if (receipt.status === "valid") expect(receipt.journal.state).toBe("complete"); expect(unlinks).toBe(0);
    const zero = plan("claude"); await expect(executeInstallPlanJournaled(zero, handlers(zero), { fs: { ...fsOps(), write: () => 0 } })).rejects.toMatchObject({ code: "journal-write-failed" });
  });

  test("rejects symlinked/private stores and keeps target-specific provider-neutral paths", () => {
    const root = home(), path = installJournalPath(root); mkdirSync(join(root, ".ein-installer"), { mode: 0o700 }); symlinkSync(join(root, "missing"), path);
    expect(inspectInstallJournal(root)).toEqual({ status: "invalid" }); expect(path).toBe(join(root, ".ein-installer", "install-execution-v1.json")); expect(path).not.toMatch(/\.pi|\.claude|\.ein\/|\.atl/);
    unlinkSync(path); writeFileSync(path, "{}", { mode: 0o644 }); expect(inspectInstallJournal(root)).toEqual({ status: "invalid" }); writeFileSync(path, "x".repeat(65537), { mode: 0o600 }); expect(inspectInstallJournal(root)).toEqual({ status: "invalid" }); const linked = `${root}-link`; roots.push(linked); symlinkSync(root, linked); expect(inspectInstallJournal(linked)).toEqual({ status: "invalid" }); rmSync(join(root, ".ein-installer"), { recursive: true }); symlinkSync(root, join(root, ".ein-installer")); expect(inspectInstallJournal(root)).toEqual({ status: "invalid" });
  });

  test("blocks startup before banner/handlers, reinstalls over a complete journal, and leaves dry-run untouched", async () => {
    const value = plan("claude"), root = value.home; await executeInstallPlanJournaled(value, handlers(value, () => ({ ok: false })));
    let effects = 0; const observations = { home: root, piAgentDir: join(root, ".pi-ein", "agent"), piAgentDirExists: false, piOwnership: { status: "absent" } as const, claudeConfigHome: join(root, ".claude-ein"), dependencies: { bun: false, pi: false, engram: false, gh: false, hypa: false, codegraph: false }, platform: { os: "darwin" as const, arch: "arm64" as const, distro: "unknown" as const, packageManager: "brew" as const, shell: "unknown" as const, shellRc: join(root, ".profile"), home: root } };
    expect(await runInstall(["--runtime", "claude"], undefined, { observations, playBanner: async () => { effects += 1; }, handlers: handlers(value, () => { effects += 1; return { ok: true }; }) })).toBe(1); expect(effects).toBe(0);
    const impossible = recovery("claude", { shared: "n", claude: "p" }), errors: string[] = [], originalError = console.error; writeFileSync(installJournalPath(root), `${JSON.stringify(impossible)}\n`, { mode: 0o600 }); console.error = (...parts: unknown[]) => { errors.push(parts.join(" ")); }; try { expect(await runInstall(["--runtime", "claude"], undefined, { observations, playBanner: async () => { effects += 1; }, handlers: handlers(value, () => { effects += 1; return { ok: true }; }) })).toBe(1); } finally { console.error = originalError; } expect(effects).toBe(0); expect(errors).toEqual(["Install recovery status: recovery-required"]); expect(inspectInstallJournal(root)).toEqual({ status: "invalid" });
    unlinkSync(installJournalPath(root)); expect(await runInstall(["--dry-run", "--runtime", "claude"], undefined, { observations, playBanner: async () => {}, writePlan: () => {} })).toBe(0); expect(inspectInstallJournal(root)).toEqual({ status: "missing" });
    const complete = plan("claude"); await executeInstallPlanJournaled(complete, handlers(complete)); const completeObservations = { ...observations, home: complete.home, claudeConfigHome: join(complete.home, ".claude-ein"), piAgentDir: join(complete.home, ".pi-ein", "agent"), platform: { ...observations.platform, home: complete.home, shellRc: join(complete.home, ".profile") } }; effects = 0; expect(await runInstall(["--yes", "--no-secrets", "--runtime", "claude"], undefined, { observations: completeObservations, playBanner: async () => { effects += 1; }, handlers: handlers(complete, () => { effects += 1; return { ok: true }; }) })).toBe(0); expect(effects).toBeGreaterThan(0); expect(inspectInstallJournal(complete.home).status).toBe("valid"); const failed = plan("pi"), base = fsOps(); let recoveryWrites = 0; const fault: InstallJournalFs = { ...base, rename(from, to) { if (new TextDecoder().decode(base.read(from)).includes('"recovery-required"')) { recoveryWrites += 1; throw new Error("fault"); } base.rename(from, to); } }; await expect(executeInstallPlanJournaled(failed, handlers(failed, (id) => ({ ok: id !== "pi.dependency.pi" })), { fs: fault })).rejects.toMatchObject({ code: "recovery-write-failed" }); expect(recoveryWrites).toBe(1); const pending = inspectInstallJournal(failed.home); expect(pending.status).toBe("valid"); if (pending.status === "valid") expect(pending.journal.state).toBe("executing"); const signaled = plan("claude"), callbacks = new Set<() => void>(), signalFs = fsOps(); let signalWrites = 0; const tracedSignals: InstallJournalFs = { ...signalFs, rename(from, to) { if (new TextDecoder().decode(signalFs.read(from)).includes('"recovery-required"')) signalWrites += 1; signalFs.rename(from, to); } }; const signals = { on(_name: string, callback: () => void) { callbacks.add(callback); return this; }, off(_name: string, callback: () => void) { callbacks.delete(callback); return this; } }; let calls = 0; await expect(executeInstallPlanJournaled(signaled, handlers(signaled, () => { calls += 1; for (const callback of callbacks) { callback(); callback(); } return { ok: true }; }), { fs: tracedSignals, signals: signals as never })).rejects.toMatchObject({ code: "recovery-required" }); expect(calls).toBe(1); expect(signalWrites).toBe(1); const signalStatus = inspectInstallJournal(signaled.home); expect(signalStatus.status).toBe("valid"); if (signalStatus.status === "valid") expect(signalStatus.journal.recoveryCode).toBe("interrupted");
  });
});
