import { createHash } from "node:crypto";
import { lstatSync, readFileSync, realpathSync } from "node:fs";
import { isAbsolute, relative, resolve, sep } from "node:path";
import typescript, { type SourceFile } from "typescript";

import type { CleanerEnvironmentEvidence } from "./cleaner-environment-evidence.ts";
import { cleanerScriptRegions, padCleanerScriptRegion } from "./cleaner-script-regions.ts";
import { projectProjectState } from "./project-state.ts";

export const CLEANER_DUPLICATION_EVIDENCE_VERSION = "cleaner-duplication-evidence/v1" as const;
const { createScanner, createSourceFile, LanguageVariant, ScriptKind, ScriptTarget, SyntaxKind } = typescript;
export const CLEANER_DUPLICATION_DEFINITION = Object.freeze({
	id: "exact-structural-token-clone-js-ts/v1", comparison: "bounded-contiguous-typescript-token-runs", identifiers: "exact-spelling-retained", literals: "exact-spelling-retained", trivia: "ignored", semanticDuplication: "not-measured", minimumTokens: "cost-and-precision-bound-not-a-quality-threshold", vue: "script-and-script-setup-only", astro: "initial-frontmatter-and-safe-inline-script-only", jscpd: "unnecessary-unless-acceptance-shows-material-misses-or-performance-issues",
} as const);

type Limits = { minTokens: number; maxFiles: number; maxBytes: number; maxTokens: number; maxWindows: number; maxCandidatePairs: number; maxGroups: number; maxDurationMs: number };
// maxDurationMs: 5000, no 500. Es el ÚNICO presupuesto que depende de la
// máquina — el resto (ficheros, bytes, tokens, ventanas, pares, nodos AST) son
// deterministas y son los que de verdad acotan el trabajo: a escala máxima,
// duplicación aborta por pares candidatos y complejidad tarda ~70 ms medidos.
// Con 500 ms, un runner de CI cargado (10x más lento) convertía una recogida
// correcta en un fallo: tres veces en una semana. La duración solo tiene que
// cazar patología que se cuele entre los presupuestos de conteo, y 5 s sobre un
// peor caso medido de 70 ms sigue haciéndolo.
const DEFAULT_LIMITS: Readonly<Limits> = Object.freeze({ minTokens: 40, maxFiles: 32, maxBytes: 1024 * 1024, maxTokens: 200_000, maxWindows: 200_000, maxCandidatePairs: 200_000, maxGroups: 1_000, maxDurationMs: 5_000 });
type Span = Readonly<{ startOffset: number; endOffset: number; startLine: number; startColumn: number; endLine: number; endColumn: number }>;
type Occurrence = Readonly<{ identity: string; path: string; span: Span; tokenCount: number; lineCount: number }>;
export type CleanerDuplicationEvidence = Readonly<{ version: typeof CLEANER_DUPLICATION_EVIDENCE_VERSION; collectorKind: "exact-structural-duplication"; definition: typeof CLEANER_DUPLICATION_DEFINITION; sourceState: CleanerEnvironmentEvidence["sourceState"]; scope: Readonly<{ identity: string; inputDigest: Readonly<{ algorithm: "sha256"; digest: string }>; files: readonly Readonly<{ path: string; sha256: string }>[] }>; groups: readonly Readonly<{ identity: string; tokenCount: number; occurrences: readonly Occurrence[]; pairs: readonly Readonly<{ identity: string; occurrenceIdentities: readonly [string, string] }>[] }>[]; aggregate: Readonly<{ groups: number; pairs: number; occurrences: number; clonedTokens: number }>; budget: Readonly<Limits & { observedFiles: number; observedBytes: number; observedTokens: number; observedWindows: number; observedCandidatePairs: number; observedGroups: number; truncated: false; durationExceeded: boolean }>; outputIdentity: Readonly<{ algorithm: "sha256"; digest: string }> }>;

type Token = { key: string; start: number; end: number };
type Segment = { id: string; path: string; file: SourceFile; tokens: Token[] };
type Position = { segment: Segment; index: number };
type Run = { left: Position; right: Position; count: number; fingerprint: string };
const hash = (value: string | Uint8Array): string => createHash("sha256").update(value).digest("hex");
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value)) freeze(child); } return value; }
// El presupuesto de duración se REPORTA al terminar; no se lanza. Antes el check
// final juntaba dos hechos distintos en un solo `throw`:
//   · el stateRef cambió = la evidencia describe un árbol que ya no existe.
//     Es correctitud, y sigue siendo fatal (fail closed).
//   · tardó de más = rendimiento. Al llegar al final el trabajo YA está hecho y
//     es válido para el estado que midió; tirarlo solo desperdicia lo gastado, y
//     en un runner cargado convertía una ejecución correcta en un fallo.
// La protección contra runaway no cambia: sigue lanzando DENTRO de los bucles,
// que es donde abortar aún ahorra algo. Mismo patrón que cleaner-test-evidence,
// que ya reportaba `durationExceeded` como booleano.
function expired(started: number, limits: Limits): boolean { return performance.now() - started > limits.maxDurationMs; }
function inside(root: string, target: string): boolean { const value = relative(root, target); return value !== "" && value !== ".." && !value.startsWith(`..${sep}`) && !isAbsolute(value); }
function order(position: Position): string { return `${position.segment.path}\0${position.segment.id}\0${String(position.index).padStart(10, "0")}`; }
function contained(run: Run, outer: Run): boolean { return run.left.segment === outer.left.segment && run.right.segment === outer.right.segment && run.left.index >= outer.left.index && run.left.index + run.count <= outer.left.index + outer.count && run.right.index >= outer.right.index && run.right.index + run.count <= outer.right.index + outer.count; }

function occurrence(position: Position, count: number): Occurrence {
	const first = position.segment.tokens[position.index]!, last = position.segment.tokens[position.index + count - 1]!; const begin = position.segment.file.getLineAndCharacterOfPosition(first.start), end = position.segment.file.getLineAndCharacterOfPosition(last.end); const span = { startOffset: first.start, endOffset: last.end, startLine: begin.line + 1, startColumn: begin.character + 1, endLine: end.line + 1, endColumn: end.character + 1 }; return { identity: `clone-occurrence-v1:sha256:${hash(`${position.segment.path}\0${first.start}\0${last.end}\0${count}`)}`, path: position.segment.path, span, tokenCount: count, lineCount: end.line - begin.line + 1 };
}

export function collectCleanerDuplicationEvidence(environment: CleanerEnvironmentEvidence, paths?: readonly string[], budget: Partial<Limits> = {}): CleanerDuplicationEvidence {
	const limits = { ...DEFAULT_LIMITS, ...budget }; if (Object.values(limits).some((value) => !Number.isInteger(value) || value < 1)) throw new Error("Cleaner duplication budget must contain positive integers"); const started = performance.now(); const current = projectProjectState({ cwd: environment.scope.root }); if (current.git.stateRef !== environment.sourceState.stateRef || current.git.quality !== "current") throw new Error("Cleaner duplication source state is stale");
	const available = new Map(environment.scope.files.map((file) => [file.path, file.sha256])); const selected = paths ? [...paths] : [...available.keys()]; if (!selected.length || selected.length > limits.maxFiles || new Set(selected).size !== selected.length) throw new Error("Cleaner duplication file scope is empty, duplicate, or over budget"); selected.sort((a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b))); const files = selected.map((path) => { const sha256 = available.get(path); if (!sha256) throw new Error("Duplication source is outside current bounded environment evidence"); return { path, sha256 }; });
	let bytes = 0, tokenCount = 0, windows = 0, candidatePairs = 0; const segments: Segment[] = [];
	for (const input of files) { const target = resolve(environment.scope.root, input.path); if (!inside(environment.scope.root, target)) throw new Error("Duplication source path escapes environment scope"); const stat = lstatSync(target); if (!stat.isFile() || stat.isSymbolicLink() || realpathSync(target) !== target) throw new Error("Duplication source is not a current regular file"); const content = readFileSync(target); bytes += content.byteLength; if (bytes > limits.maxBytes) throw new Error("Cleaner duplication byte budget exceeded"); if (hash(content) !== input.sha256) throw new Error("Duplication source digest is stale"); const source = content.toString("utf8"); if (!Buffer.from(source, "utf8").equals(content)) throw new Error("Duplication source is not valid UTF-8");
		for (const [regionIndex, region] of cleanerScriptRegions(input.path, source).entries()) { const file = createSourceFile(input.path, padCleanerScriptRegion(source, region), ScriptTarget.Latest, true, region.kind); if ((file as SourceFile & { readonly parseDiagnostics: readonly unknown[] }).parseDiagnostics.length) throw new Error(`Malformed source prevents reliable clone boundaries: ${input.path}`); const scanner = createScanner(ScriptTarget.Latest, true, region.kind === ScriptKind.JSX || region.kind === ScriptKind.TSX ? LanguageVariant.JSX : LanguageVariant.Standard, source.slice(region.start, region.end)); const tokens: Token[] = []; for (let kind = scanner.scan(); kind !== SyntaxKind.EndOfFileToken; kind = scanner.scan()) tokens.push({ key: `${kind}:${scanner.getTokenText()}`, start: region.start + scanner.getTokenPos(), end: region.start + scanner.getTextPos() }); tokenCount += tokens.length; if (tokenCount > limits.maxTokens) throw new Error("Cleaner duplication token budget exceeded"); segments.push({ id: `${input.path}:${regionIndex}`, path: input.path, file, tokens }); }
	}
	const seeds = new Map<string, Position[]>(); for (const segment of segments) for (let index = 0; index + limits.minTokens <= segment.tokens.length; index++) { if (++windows > limits.maxWindows) throw new Error("Cleaner duplication window budget exceeded"); const key = hash(segment.tokens.slice(index, index + limits.minTokens).map((token) => token.key).join("\0")); const positions = seeds.get(key) ?? []; positions.push({ segment, index }); seeds.set(key, positions); }
	const found = new Map<string, Run>(); for (const positions of seeds.values()) for (let i = 0; i < positions.length; i++) for (let j = i + 1; j < positions.length; j++) { if (++candidatePairs > limits.maxCandidatePairs) throw new Error("Cleaner duplication candidate-pair budget exceeded"); let left = positions[i]!, right = positions[j]!; if (order(left) > order(right)) [left, right] = [right, left]; let before = 0; while (left.index > before && right.index > before && left.segment.tokens[left.index - before - 1]!.key === right.segment.tokens[right.index - before - 1]!.key) before++; let count = limits.minTokens; while (left.index + count < left.segment.tokens.length && right.index + count < right.segment.tokens.length && left.segment.tokens[left.index + count]!.key === right.segment.tokens[right.index + count]!.key) count++; left = { ...left, index: left.index - before }; right = { ...right, index: right.index - before }; count += before; if (left.segment === right.segment && left.index + count > right.index) continue; const key = `${order(left)}\0${order(right)}\0${count}`; found.set(key, { left, right, count, fingerprint: hash(left.segment.tokens.slice(left.index, left.index + count).map((token) => token.key).join("\0")) }); if (expired(started, limits)) throw new Error("Cleaner duplication duration budget exceeded"); }
	const maximal: Run[] = []; for (const run of [...found.values()].sort((a, b) => b.count - a.count || Buffer.compare(Buffer.from(`${order(a.left)}\0${order(a.right)}`), Buffer.from(`${order(b.left)}\0${order(b.right)}`)))) if (!maximal.some((outer) => contained(run, outer))) maximal.push(run);
	const grouped = new Map<string, Run[]>(); for (const run of maximal) { const key = `${run.fingerprint}:${run.count}`; const group = grouped.get(key) ?? []; group.push(run); grouped.set(key, group); } if (grouped.size > limits.maxGroups) throw new Error("Cleaner duplication group budget exceeded");
	const groups = [...grouped.entries()].map(([key, runs]) => { const all = runs.flatMap((run) => [run.left, run.right]).sort((a, b) => Buffer.compare(Buffer.from(order(a)), Buffer.from(order(b)))); const selectedPositions: Position[] = []; for (const position of all) if (!selectedPositions.some((prior) => prior.segment === position.segment && position.index < prior.index + runs[0]!.count && prior.index < position.index + runs[0]!.count)) selectedPositions.push(position); const occurrences = selectedPositions.map((position) => occurrence(position, runs[0]!.count)); const byOrder = new Map(selectedPositions.map((position, index) => [order(position), occurrences[index]!])); const pairs = runs.flatMap((run) => { const left = byOrder.get(order(run.left)), right = byOrder.get(order(run.right)); if (!left || !right) return []; const occurrenceIdentities = [left.identity, right.identity] as const; return [{ identity: `clone-pair-v1:sha256:${hash(occurrenceIdentities.join("\0"))}`, occurrenceIdentities }]; }); return { identity: `clone-group-v1:sha256:${hash(`${key}\0${occurrences.map((item) => item.identity).join("\0")}`)}`, tokenCount: runs[0]!.count, occurrences, pairs }; }).filter((group) => group.pairs.length).sort((a, b) => Buffer.compare(Buffer.from(a.identity), Buffer.from(b.identity)));
	const inputDigest = { algorithm: "sha256" as const, digest: hash(JSON.stringify(files)) }; const base = { version: CLEANER_DUPLICATION_EVIDENCE_VERSION, collectorKind: "exact-structural-duplication" as const, definition: CLEANER_DUPLICATION_DEFINITION, sourceState: environment.sourceState, scope: { identity: `duplication-scope-v1:sha256:${inputDigest.digest}`, inputDigest, files }, groups, aggregate: { groups: groups.length, pairs: groups.reduce((sum, group) => sum + group.pairs.length, 0), occurrences: groups.reduce((sum, group) => sum + group.occurrences.length, 0), clonedTokens: groups.reduce((sum, group) => sum + group.tokenCount * group.occurrences.length, 0) }, budget: { ...limits, observedFiles: files.length, observedBytes: bytes, observedTokens: tokenCount, observedWindows: windows, observedCandidatePairs: candidatePairs, observedGroups: groups.length, truncated: false as const, durationExceeded: expired(started, limits) } }; const after = projectProjectState({ cwd: environment.scope.root }); if (after.git.stateRef !== environment.sourceState.stateRef) throw new Error("Cleaner duplication source state changed"); return freeze({ ...base, outputIdentity: { algorithm: "sha256" as const, digest: hash(JSON.stringify(base)) } });
}
