import { createHash } from "node:crypto";
import { lstatSync, readFileSync, realpathSync } from "node:fs";
import { isAbsolute, join, relative, resolve, sep } from "node:path";

import type { CleanerEnvironmentEvidence } from "./cleaner-environment-evidence.ts";
import { extendCleanerTestPlanInvocation, type CleanerTestBinding, type CleanerTestEvidence, type CleanerTestPlan } from "./cleaner-test-evidence.ts";
import { projectProjectState } from "./project-state.ts";

export const CLEANER_COVERAGE_EVIDENCE_VERSION = "cleaner-coverage-evidence/v1" as const;
type Limits = { maxArtifactBytes: number; maxFiles: number; maxRecords: number; maxFunctions: number };
const DEFAULT_LIMITS: Readonly<Limits> = Object.freeze({ maxArtifactBytes: 2 * 1024 * 1024, maxFiles: 256, maxRecords: 100_000, maxFunctions: 10_000 });
type Metric = Readonly<{ found: number; hit: number; percentage: number | null }>;
type FunctionCoverage = Readonly<{ line: number; name: string; hits: number; identity: string; mapping: Readonly<{ confidence: "provisional-location"; limitation: "lcov-name-and-line-not-ast-identity" }> }>;
export type CleanerCoverageLine = Readonly<{ line: number; hits: number }>;
type FileCoverage = Readonly<{ path: string; sourceDigest: Readonly<{ algorithm: "sha256"; digest: string }>; lines: Metric; lineRecords: readonly CleanerCoverageLine[]; branches: Metric; functions: Metric; functionRecords: readonly FunctionCoverage[] }>;
export type CleanerCoveragePlan = Readonly<{ status: "available" | "unavailable"; reason: "planned" | "test-invocation-unavailable"; runner: "bun" | "vitest"; argv?: readonly [string, ...string[]]; outputDirectory?: string; artifactPath?: string; testPlan?: CleanerTestPlan; invocationIdentity?: Readonly<{ algorithm: "sha256"; digest: string }> }>;
export type CleanerCoverageEvidence = Readonly<{
	version: typeof CLEANER_COVERAGE_EVIDENCE_VERSION; collectorKind: "lcov-coverage"; status: "available" | "unavailable"; freshness: "current" | "stale" | "unavailable"; reason: "collected" | "tests-failed-coverage-only" | "test-evidence-unavailable" | "source-state-changed";
	runner: "bun" | "vitest"; qualityOutcome: "tests-passed" | "tests-failed" | "unavailable"; sourceState: Readonly<{ kind: "git-state"; stateRef: string; freshness: "current" | "stale" | "unavailable" }>; testEvidenceIdentity: Readonly<{ algorithm: "sha256"; digest: string }> | null;
	files: readonly FileCoverage[]; totals: Readonly<{ lines: Metric; branches: Metric; functions: Metric }>; artifactIdentity: Readonly<{ algorithm: "sha256"; digest: string }> | null; outputIdentity: Readonly<{ algorithm: "sha256"; digest: string }>; budget: Readonly<Limits & { observedArtifactBytes: number; observedFiles: number; observedRecords: number; observedFunctions: number }>;
}>;

function hash(value: unknown): string { return createHash("sha256").update(value instanceof Uint8Array ? value : typeof value === "string" ? value : JSON.stringify(value)).digest("hex"); }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value)) freeze(child); } return value; }
function inside(root: string, target: string): boolean { const value = relative(root, target); return value !== "" && value !== ".." && !value.startsWith(`..${sep}`) && !isAbsolute(value); }
function safePath(value: string): boolean { return !!value && !isAbsolute(value) && !value.includes("\\") && !value.split("/").some((part) => part === ".." || ["coverage", "dist", "build", "generated", "node_modules", "vendor"].includes(part.toLowerCase())) && !/[\u0000-\u001f\u007f]/.test(value); }
function metric(found: number, hit: number): Metric { return { found, hit, percentage: found === 0 ? null : Number(((hit / found) * 100).toFixed(6)) }; }
function outputDirectory(root: string, input: string, approved: readonly string[]): string { const absolute = resolve(input); const stat = lstatSync(absolute); if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error("Cleaner coverage output directory must be an existing regular directory"); const canonical = realpathSync(absolute), canonicalRoot = realpathSync(root); if ((canonical === canonicalRoot || inside(canonicalRoot, canonical)) && !approved.map((item) => realpathSync(resolve(item))).includes(canonical)) throw new Error("Cleaner coverage output directory must be repository-external or explicitly approved"); return canonical; }

export function planCleanerCoverageEvidence(environment: CleanerEnvironmentEvidence, testPlan: CleanerTestPlan, input: Readonly<{ outputDirectory: string; approvedEvidenceDirectories?: readonly string[] }>): CleanerCoveragePlan {
	if (testPlan.status !== "available" || !testPlan.argv) return freeze({ status: "unavailable", reason: "test-invocation-unavailable", runner: testPlan.runner });
	const directory = outputDirectory(environment.scope.root, input.outputDirectory, input.approvedEvidenceDirectories ?? []);
	const suffix = testPlan.runner === "bun" ? ["--coverage", "--coverage-reporter=lcov", `--coverage-dir=${directory}`] : ["--coverage.enabled", "--coverage.reporter=lcov", `--coverage.reportsDirectory=${directory}`];
	const extended = extendCleanerTestPlanInvocation(testPlan, suffix); const artifactPath = join(directory, "lcov.info");
	return freeze({ status: "available", reason: "planned", runner: testPlan.runner, argv: extended.argv, outputDirectory: directory, artifactPath, testPlan: extended, invocationIdentity: extended.invocationIdentity });
}

type Parsed = { path: string; lines: Map<number, number>; branches: Map<string, number>; declarations: Map<string, number>; hits: Map<string, number>; summaries: Map<string, number> };
function count(value: string, label: string): number { if (!/^(?:0|[1-9]\d*)$/.test(value)) throw new Error(`Invalid LCOV ${label}`); const result = Number(value); if (!Number.isSafeInteger(result)) throw new Error(`Invalid LCOV ${label}`); return result; }
function putUnique<T>(map: Map<string | number, T>, key: string | number, value: T): void { const prior = map.get(key); if (prior !== undefined && prior !== value) throw new Error("Conflicting duplicate LCOV declaration"); map.set(key, value); }
function parse(source: string, limits: Limits): { files: Parsed[]; records: number } {
	const files: Parsed[] = []; let current: Parsed | undefined; let records = 0;
	for (const raw of source.split(/\r?\n/)) { if (!raw) continue; if (++records > limits.maxRecords) throw new Error("LCOV record budget exceeded"); if (raw === "end_of_record") { if (!current) throw new Error("LCOV record outside source file"); files.push(current); current = undefined; if (files.length > limits.maxFiles) throw new Error("LCOV file budget exceeded"); continue; } const split = raw.indexOf(":"); if (split < 0) throw new Error("Malformed LCOV record"); const tag = raw.slice(0, split), value = raw.slice(split + 1);
		if (tag === "TN" && !current && value === "") continue;
		if (tag === "SF") { if (current || !safePath(value)) throw new Error("Unsafe or malformed LCOV source path"); current = { path: value, lines: new Map(), branches: new Map(), declarations: new Map(), hits: new Map(), summaries: new Map() }; continue; }
		if (!current) throw new Error("LCOV record outside source file");
		if (tag === "DA") { const parts = value.split(","); if (parts.length !== 2) throw new Error("Unsupported LCOV DA ambiguity"); putUnique(current.lines, count(parts[0]!, "line"), count(parts[1]!, "line hits")); }
		else if (tag === "BRDA") { const parts = value.split(","); if (parts.length !== 4 || !/^(?:0|[1-9]\d*)$/.test(parts[1]!) || !/^(?:0|[1-9]\d*)$/.test(parts[2]!)) throw new Error("Malformed LCOV branch"); const line = count(parts[0]!, "branch line"), hits = parts[3] === "-" ? 0 : count(parts[3]!, "branch hits"); putUnique(current.branches, `${line}:${parts[1]}:${parts[2]}`, hits); }
		else if (tag === "FN") { const splitAt = value.indexOf(","); if (splitAt < 1 || value.indexOf(",", splitAt + 1) >= 0) throw new Error("Unsupported LCOV function ambiguity"); const line = count(value.slice(0, splitAt), "function line"), name = value.slice(splitAt + 1); if (!name || /[\u0000-\u001f\u007f]/.test(name)) throw new Error("Invalid LCOV function name"); putUnique(current.declarations, `${line}\0${name}`, line); }
		else if (tag === "FNDA") { const splitAt = value.indexOf(","); if (splitAt < 1) throw new Error("Malformed LCOV function hits"); const hits = count(value.slice(0, splitAt), "function hits"), name = value.slice(splitAt + 1); putUnique(current.hits, name, hits); }
		else if (["LF", "LH", "BRF", "BRH", "FNF", "FNH"].includes(tag)) putUnique(current.summaries, tag, count(value, "summary"));
		else throw new Error(`Unsupported LCOV record: ${tag}`);
	}
	if (current || !files.length || new Set(files.map((file) => file.path)).size !== files.length) throw new Error("Malformed or duplicate LCOV source record"); return { files, records };
}

export function collectCleanerCoverageEvidence(environment: CleanerEnvironmentEvidence, plan: CleanerCoveragePlan, testEvidence: CleanerTestEvidence, artifactPath: string, binding?: CleanerTestBinding, budget: Partial<Limits> = {}): CleanerCoverageEvidence {
	if (plan.status !== "available" || !plan.artifactPath || !plan.invocationIdentity) throw new Error("Cleaner coverage invocation was not planned"); const limits = { ...DEFAULT_LIMITS, ...budget }; if (Object.values(limits).some((value) => !Number.isInteger(value) || value < 1)) throw new Error("Cleaner coverage budget must contain positive integers");
	const common = { version: CLEANER_COVERAGE_EVIDENCE_VERSION, collectorKind: "lcov-coverage" as const, runner: plan.runner, sourceState: environment.sourceState }; const unavailable = (reason: "test-evidence-unavailable" | "source-state-changed", freshness: "stale" | "unavailable"): CleanerCoverageEvidence => { const base = { ...common, status: "unavailable" as const, freshness, reason, qualityOutcome: "unavailable" as const, sourceState: { ...environment.sourceState, freshness }, testEvidenceIdentity: null, files: [], totals: { lines: metric(0, 0), branches: metric(0, 0), functions: metric(0, 0) }, artifactIdentity: null, budget: { ...limits, observedArtifactBytes: 0, observedFiles: 0, observedRecords: 0, observedFunctions: 0 } }; return freeze({ ...base, outputIdentity: { algorithm: "sha256", digest: hash(base) } }); };
	if (testEvidence.status !== "available" || testEvidence.freshness !== "current" || testEvidence.invocationIdentity.digest !== plan.invocationIdentity.digest || !testEvidence.result) return unavailable("test-evidence-unavailable", "unavailable"); const current = projectProjectState({ cwd: environment.scope.root }); if (!binding || binding.preStateRef !== environment.sourceState.stateRef || binding.postStateRef !== binding.preStateRef || current.git.stateRef !== binding.postStateRef || testEvidence.sourceState.stateRef !== binding.postStateRef) return unavailable("source-state-changed", "stale");
	if (resolve(artifactPath) !== plan.artifactPath) throw new Error("Artifact does not match planned LCOV output"); const stat = lstatSync(artifactPath); if (!stat.isFile() || stat.isSymbolicLink() || stat.size > limits.maxArtifactBytes) throw new Error("Invalid or oversized LCOV artifact"); const bytes = readFileSync(artifactPath), parsed = parse(bytes.toString("utf8"), limits); const known = new Map(environment.scope.files.map((file) => [file.path, file.sha256])); let functionCount = 0;
		const files = parsed.files.map((file): FileCoverage => { const expected = known.get(file.path); if (!expected) throw new Error("LCOV source unavailable in current bounded evidence"); const target = resolve(environment.scope.root, file.path); if (!inside(environment.scope.root, target) || realpathSync(target) !== target || !lstatSync(target).isFile()) throw new Error("LCOV source is missing or unavailable"); const actual = hash(readFileSync(target)); if (actual !== expected) throw new Error("LCOV source digest does not match current evidence"); const byName = new Map<string, [string, number][]>(); for (const [key, line] of file.declarations) { const name = key.split("\0")[1]!; byName.set(name, [...(byName.get(name) ?? []), [key, line]]); } const functions = [...file.declarations].map(([key, line]) => { const name = key.split("\0")[1]!; const matches = byName.get(name)!; if (matches.length !== 1 || !file.hits.has(name)) throw new Error("Unsupported ambiguous LCOV function mapping"); const hits = file.hits.get(name)!; return { line, name, hits, identity: `location-v1:sha256:${hash(`${file.path}\0${expected}\0${line}\0${name}`)}`, mapping: { confidence: "provisional-location" as const, limitation: "lcov-name-and-line-not-ast-identity" as const } }; }).sort((a, b) => a.line - b.line || a.name.localeCompare(b.name, "en")); if (file.hits.size !== functions.length || (functionCount += functions.length) > limits.maxFunctions) throw new Error("LCOV function budget or mapping mismatch"); const lineRecords = [...file.lines].map(([line, hits]) => ({ line, hits })).sort((a, b) => a.line - b.line); const lines = metric(lineRecords.length, lineRecords.filter(({ hits }) => hits > 0).length), branches = metric(file.branches.size, [...file.branches.values()].filter((hits) => hits > 0).length); const declaredFunctions = metric(functions.length, functions.filter((item) => item.hits > 0).length), functionMetric = functions.length ? declaredFunctions : metric(file.summaries.get("FNF") ?? 0, file.summaries.get("FNH") ?? 0); if (functionMetric.hit > functionMetric.found) throw new Error("Conflicting LCOV function summary"); for (const [tag, actualValue] of [["LF", lines.found], ["LH", lines.hit], ["BRF", branches.found], ["BRH", branches.hit]] as const) if (file.summaries.has(tag) && file.summaries.get(tag) !== actualValue) throw new Error("Conflicting LCOV summary"); if (functions.length) for (const [tag, actualValue] of [["FNF", functionMetric.found], ["FNH", functionMetric.hit]] as const) if (file.summaries.has(tag) && file.summaries.get(tag) !== actualValue) throw new Error("Conflicting LCOV summary"); return { path: file.path, sourceDigest: { algorithm: "sha256", digest: expected }, lines, lineRecords, branches, functions: functionMetric, functionRecords: functions }; }).sort((a, b) => a.path.localeCompare(b.path, "en"));
	const total = (key: "lines" | "branches" | "functions"): Metric => metric(files.reduce((sum, file) => sum + file[key].found, 0), files.reduce((sum, file) => sum + file[key].hit, 0)); const failed = testEvidence.result.failed > 0 || (testEvidence.exitOutcome?.exitCode ?? 0) !== 0; const base = { ...common, status: "available" as const, freshness: "current" as const, reason: failed ? "tests-failed-coverage-only" as const : "collected" as const, qualityOutcome: failed ? "tests-failed" as const : "tests-passed" as const, testEvidenceIdentity: testEvidence.outputIdentity, files, totals: { lines: total("lines"), branches: total("branches"), functions: total("functions") }, artifactIdentity: { algorithm: "sha256" as const, digest: hash(bytes) }, budget: { ...limits, observedArtifactBytes: bytes.byteLength, observedFiles: files.length, observedRecords: parsed.records, observedFunctions: functionCount } }; return freeze({ ...base, outputIdentity: { algorithm: "sha256", digest: hash(base) } });
}
