import { createHash } from "node:crypto";
import { extname } from "node:path";

import type { CleanerComplexityEvidence, CleanerFunctionComplexity } from "./cleaner-complexity-evidence.ts";
import type { CleanerCoverageEvidence, CleanerCoverageLine } from "./cleaner-coverage-evidence.ts";

export const CLEANER_CRAP_EVIDENCE_VERSION = "cleaner-crap-evidence/v1" as const;
export const CLEANER_CRAP_FORMULA = Object.freeze({ id: "crap-standard/v1", expression: "complexity^2 * (1 - coverage)^3 + complexity", coverage: "exact AST-span LCOV DA executable-line fraction 0..1", rounding: "exact coverage input; reported coverage and CRAP nearest 0.000001" } as const);
type Limits = { maxFunctions: number; maxLineRecords: number };
const DEFAULT_LIMITS: Readonly<Limits> = Object.freeze({ maxFunctions: 10_000, maxLineRecords: 100_000 });
export type CrapUnavailableReason = "coverage-file-missing" | "no-da-denominator" | "same-line-ambiguous" | "nested-function-line-ambiguous" | "framework-offset-unproven" | "declaration-only-line-ambiguous";
type Identity = Readonly<{ algorithm: "sha256"; digest: string }>;
type Measured = Readonly<{ identity: string; functionIdentity: string; path: string; span: CleanerFunctionComplexity["span"]; complexity: number; coveredLines: number; totalExecutableLines: number; coverageFraction: number; crap: number; mappingConfidence: "exact-path-digest-ast-span-da-lines" }>;
type Unavailable = Readonly<{ functionIdentity: string; path: string; span: CleanerFunctionComplexity["span"]; complexity: number; reason: CrapUnavailableReason }>;
export type CleanerCrapEvidence = Readonly<{ version: typeof CLEANER_CRAP_EVIDENCE_VERSION; collectorKind: "function-crap"; formula: typeof CLEANER_CRAP_FORMULA; sourceState: CleanerComplexityEvidence["sourceState"]; inputs: Readonly<{ complexity: Identity; coverage: Identity }>; measured: readonly Measured[]; unavailable: readonly Unavailable[]; aggregate: Readonly<{ count: number; max: number | null; distribution: readonly Readonly<{ crap: number; count: number }>[]; unavailableCount: number; unavailableReasons: Readonly<Partial<Record<CrapUnavailableReason, number>>> }>; budget: Readonly<Limits & { observedFunctions: number; observedLineRecords: number }>; outputIdentity: Identity }>;

function hash(value: unknown): string { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value)) freeze(child); } return value; }
function validIdentity(value: unknown): value is Identity { return !!value && typeof value === "object" && (value as Identity).algorithm === "sha256" && /^[a-f0-9]{64}$/.test((value as Identity).digest); }
function validPacketIdentity(value: { outputIdentity: Identity }): boolean { const { outputIdentity, ...base } = value; return validIdentity(outputIdentity) && hash(base) === outputIdentity.digest; }
function validFunction(fn: CleanerFunctionComplexity): boolean { const span = fn?.span; return typeof fn?.identity === "string" && typeof fn.path === "string" && Number.isSafeInteger(fn.complexity) && fn.complexity >= 1 && !!span && [span.startLine, span.startColumn, span.endLine, span.endColumn].every((value) => Number.isSafeInteger(value) && value >= 1) && (span.endLine > span.startLine || span.endLine === span.startLine && span.endColumn >= span.startColumn) && typeof fn.coverageMapping?.ambiguous === "boolean"; }
function validLine(record: CleanerCoverageLine): boolean { return Number.isSafeInteger(record?.line) && record.line >= 1 && Number.isSafeInteger(record.hits) && record.hits >= 0; }
function round(value: number): number { return Number(value.toFixed(6)); }
export function calculateCrap(complexity: number, coverage: number): number { if (!Number.isSafeInteger(complexity) || complexity < 1 || !Number.isFinite(coverage) || coverage < 0 || coverage > 1) throw new Error("Invalid CRAP formula input"); return round(complexity ** 2 * (1 - coverage) ** 3 + complexity); }

export function deriveCleanerCrapEvidence(complexity: CleanerComplexityEvidence, coverage: CleanerCoverageEvidence, budget: Partial<Limits> = {}): CleanerCrapEvidence {
	const limits = { ...DEFAULT_LIMITS, ...budget }; if (Object.values(limits).some((value) => !Number.isInteger(value) || value < 1)) throw new Error("Cleaner CRAP budget must contain positive integers");
	if (complexity?.version !== "cleaner-complexity-evidence/v1" || coverage?.version !== "cleaner-coverage-evidence/v1" || coverage.status !== "available" || coverage.freshness !== "current" || complexity.sourceState?.freshness !== "current" || complexity.sourceState.stateRef !== coverage.sourceState?.stateRef || !validPacketIdentity(complexity) || !validPacketIdentity(coverage)) throw new Error("Cleaner CRAP inputs are stale, malformed, or incompatible");
	if (!Array.isArray(complexity.functions) || !Array.isArray(complexity.scope?.files) || !Array.isArray(coverage.files) || complexity.functions.length > limits.maxFunctions || complexity.functions.some((fn) => !validFunction(fn))) throw new Error("Malformed or over-budget CRAP complexity input");
	const scope = new Map(complexity.scope.files.map((file) => [file.path, file.sha256])); const files = new Map<string, CleanerCoverageEvidence["files"][number]>(); let observedLineRecords = 0;
	for (const file of coverage.files) { const records: readonly unknown[] = file?.lineRecords; if (!file || typeof file.path !== "string" || !validIdentity(file.sourceDigest) || !Array.isArray(records) || records.some((line) => !validLine(line as CleanerCoverageLine)) || new Set(records.map((line) => (line as CleanerCoverageLine).line)).size !== records.length) throw new Error("Malformed CRAP coverage input"); observedLineRecords += records.length; if (observedLineRecords > limits.maxLineRecords || files.has(file.path)) throw new Error("Malformed or over-budget CRAP coverage input"); files.set(file.path, file); }
	for (const [path, expected] of scope) { const file = files.get(path); if (file && file.sourceDigest.digest !== expected) throw new Error("Cleaner CRAP source digest mismatch"); }
	const measured: Measured[] = [], unavailable: Unavailable[] = []; const fail = (fn: CleanerFunctionComplexity, reason: CrapUnavailableReason): void => { unavailable.push({ functionIdentity: fn.identity, path: fn.path, span: fn.span, complexity: fn.complexity, reason }); };
	for (const fn of complexity.functions) { const file = files.get(fn.path); if (!file) { fail(fn, "coverage-file-missing"); continue; } if ([".vue", ".astro"].includes(extname(fn.path).toLowerCase())) { fail(fn, "framework-offset-unproven"); continue; } if (fn.coverageMapping.ambiguous) { fail(fn, "same-line-ambiguous"); continue; }
		const nested = complexity.functions.some((other) => other !== fn && other.path === fn.path && (other.span.startLine > fn.span.startLine || other.span.startLine === fn.span.startLine && other.span.startColumn > fn.span.startColumn) && (other.span.endLine < fn.span.endLine || other.span.endLine === fn.span.endLine && other.span.endColumn <= fn.span.endColumn)); if (nested) { fail(fn, "nested-function-line-ambiguous"); continue; }
		const lines = file.lineRecords.filter(({ line }) => line >= fn.span.startLine && line <= fn.span.endLine); if (!lines.length) { fail(fn, "no-da-denominator"); continue; } if (lines.length === 1 && lines[0]!.line === fn.coverageMapping.declarationLine) { fail(fn, "declaration-only-line-ambiguous"); continue; }
		const coveredLines = lines.filter(({ hits }) => hits > 0).length, exactCoverage = coveredLines / lines.length, coverageFraction = round(exactCoverage), crap = calculateCrap(fn.complexity, exactCoverage); measured.push({ identity: `crap-function-v1:sha256:${hash(`${fn.identity}\0${file.sourceDigest.digest}\0${coveredLines}\0${lines.length}`)}`, functionIdentity: fn.identity, path: fn.path, span: fn.span, complexity: fn.complexity, coveredLines, totalExecutableLines: lines.length, coverageFraction, crap, mappingConfidence: "exact-path-digest-ast-span-da-lines" }); }
	const distribution = [...new Set(measured.map(({ crap }) => crap))].sort((a, b) => a - b).map((crap) => ({ crap, count: measured.filter((item) => item.crap === crap).length })); const unavailableReasons: Partial<Record<CrapUnavailableReason, number>> = {}; for (const item of unavailable) unavailableReasons[item.reason] = (unavailableReasons[item.reason] ?? 0) + 1;
	const base = { version: CLEANER_CRAP_EVIDENCE_VERSION, collectorKind: "function-crap" as const, formula: CLEANER_CRAP_FORMULA, sourceState: complexity.sourceState, inputs: { complexity: complexity.outputIdentity, coverage: coverage.outputIdentity }, measured, unavailable, aggregate: { count: measured.length, max: measured.length ? Math.max(...measured.map(({ crap }) => crap)) : null, distribution, unavailableCount: unavailable.length, unavailableReasons }, budget: { ...limits, observedFunctions: complexity.functions.length, observedLineRecords } }; return freeze({ ...base, outputIdentity: { algorithm: "sha256", digest: hash(base) } });
}
